window.GOMGOM_PROJECTS = [
  {
    slug: "geulttaogi",
    name: "글따오기",
    mark: "GT",
    status: "운영중",
    statusTone: "active",
    type: "macOS App",
    category: "app",
    summary: "스크린샷과 이미지에서 텍스트를 추출하고 요약, 수정, 재분석까지 연결하는 OCR 앱입니다.",
    description: "이미지 속 텍스트를 빠르게 불러오고 필요한 구역만 다시 분석할 수 있도록 만든 생산성 앱입니다. 기존 gomgom-dev Pages의 글따오기 소개 페이지를 통합 템플릿으로 정리했습니다.",
    highlights: [
      "이미지와 스크린샷의 텍스트 추출",
      "요약과 전체 내용 확인 및 직접 수정",
      "선택 영역 재분석 흐름",
      "삭제한 분석 내용 아카이브 복원"
    ],
    stack: ["macOS", "OCR", "Swift", "App Store"],
    sourceRepo: "gomgom-dev/gomgom-dev.github.io",
    repoUrl: "https://github.com/gomgom-dev/gomgom-dev.github.io/tree/main/geulttaogi",
    referenceUrl: "https://github.com/jhny-kor/jhny-kor.github.io/tree/main/geulttaogi",
    pagePath: "./geulttaogi/",
    supportUrl: "mailto:gomgomi.k.dev@gmail.com",
    policyUrl: "../privacy-policy/"
  },
  {
    slug: "opentax",
    name: "OpenTax",
    mark: "OT",
    status: "운영중",
    statusTone: "active",
    type: "Web / MCP",
    category: "site",
    summary: "대한민국 세금, 공제, 정책지원, 신고기한을 검증 가능한 지식 그래프로 묶는 웹 가이드입니다.",
    description: "jhny-kor Pages의 OpenTax를 기준으로, 세금 정보와 정책지원 데이터를 앱과 문서에서 재사용할 수 있는 표면으로 정리합니다. 공개 온톨로지, MCP endpoint, 지원 문서를 한 페이지에서 연결합니다.",
    highlights: [
      "세목, 공제, 정책지원, 신고기한의 그래프형 탐색",
      "공식 출처와 기준일 중심의 설명 구조",
      "JSON export와 MCP endpoint 연결",
      "지원, 약관, 개인정보 문서 링크 정리"
    ],
    stack: ["HTML", "CSS", "JavaScript", "MCP"],
    sourceRepo: "jhny-kor/TaxMeter",
    repoUrl: "https://github.com/jhny-kor/TaxMeter",
    referenceUrl: "https://github.com/jhny-kor/jhny-kor.github.io/tree/main/opentax",
    pagePath: "./opentax/",
    externalPage: "https://jhny-kor.github.io/opentax/",
    supportUrl: "https://github.com/jhny-kor/TaxMeter/issues",
    policyUrl: "https://jhny-kor.github.io/opentax/privacy.html"
  },
  {
    slug: "tax-ontology",
    name: "Tax Ontology",
    mark: "TO",
    status: "운영중",
    statusTone: "active",
    type: "Data Site",
    category: "data",
    summary: "TaxMeter가 재사용할 수 있는 대한민국 세금 온톨로지와 데이터 흐름을 설명하는 사이트입니다.",
    description: "세목, 제도, 용어, 기한, 출처를 ID 기반 노드로 나누고 앱, MCP, 웹에서 같은 데이터를 쓰도록 안내하는 온톨로지 페이지입니다.",
    highlights: [
      "국세와 지방세 카테고리의 구조화",
      "정책지원과 사업자 세무 흐름 연결",
      "데이터 생성, 검증, export 파이프라인 설명",
      "TaxMeter 기능과 데이터 노드의 매핑 기반"
    ],
    stack: ["Ontology", "JSON", "Graph", "Tax"],
    sourceRepo: "jhny-kor/jhny-kor.github.io",
    repoUrl: "https://github.com/jhny-kor/jhny-kor.github.io/tree/main/tax-ontology",
    referenceUrl: "https://jhny-kor.github.io/tax-ontology/",
    pagePath: "./tax-ontology/",
    supportUrl: "https://github.com/jhny-kor/TaxMeter/issues",
    policyUrl: "https://jhny-kor.github.io/opentax/privacy.html"
  },
  {
    slug: "taxmeter",
    name: "TaxMeter",
    mark: "TM",
    status: "정리중",
    statusTone: "maintenance",
    type: "Tax App",
    category: "app",
    summary: "세금 기준, 위험 신호, 절세 체크리스트를 앱 표면으로 제공하기 위한 Python 기반 프로젝트입니다.",
    description: "TaxMeter는 OpenTax와 Tax Ontology의 데이터 표면을 실제 사용자 기능으로 연결하는 세금 도구 프로젝트입니다. 현재 대표 페이지에서는 레포, 온톨로지, 지원 경로를 한곳에 묶습니다.",
    highlights: [
      "세금 기준과 공식 출처 기반 설명",
      "OpenTax 온톨로지와 앱 기능 연결",
      "Python 기반 데이터 처리 흐름",
      "이슈 트래커를 통한 기준 누락 및 오류 접수"
    ],
    stack: ["Python", "Tax", "OpenTax", "Data"],
    sourceRepo: "jhny-kor/TaxMeter",
    repoUrl: "https://github.com/jhny-kor/TaxMeter",
    referenceUrl: "https://github.com/jhny-kor/TaxMeter",
    pagePath: "./taxmeter/",
    supportUrl: "https://github.com/jhny-kor/TaxMeter/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "auto-coin-trading",
    name: "AutoCoinTrading",
    mark: "AC",
    status: "참조",
    statusTone: "reference",
    type: "Trading Bot",
    category: "automation",
    summary: "비트코인, 이더리움, 리플 등 코인 자동매매 전략과 운영 자동화를 다루는 Python 프로젝트입니다.",
    description: "jhny-kor의 AutoCoinTrading 공개 레포를 기준으로 코인 자동매매 봇의 목적, 실행 표면, 운영 문서 진입점을 대표 Pages 안에 정리했습니다.",
    highlights: [
      "코인 자동매매 프로그램",
      "AI agent, bitcoin, ethereum, ripple 토픽 기반",
      "거래 전략과 운영 자동화 분리",
      "GitHub 레포를 원본 문서로 연결"
    ],
    stack: ["Python", "Trading", "Automation", "Crypto"],
    sourceRepo: "jhny-kor/AutoCoinTrading",
    repoUrl: "https://github.com/jhny-kor/AutoCoinTrading",
    referenceUrl: "https://github.com/jhny-kor/AutoCoinTrading",
    pagePath: "./auto-coin-trading/",
    supportUrl: "https://github.com/jhny-kor/AutoCoinTrading/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "auto-stock-trading",
    name: "AutoStockTrading",
    mark: "AS",
    status: "참조",
    statusTone: "reference",
    type: "Trading Bot",
    category: "automation",
    summary: "주식 자동매매 운영 흐름과 분석 작업을 묶는 Python 기반 프로젝트입니다.",
    description: "AutoStockTrading은 주식 매매 자동화와 데이터 수집 흐름을 위한 레포입니다. 대표 Pages에서는 실행 코드보다 프로젝트 목적과 원본 저장소 링크를 우선 제공합니다.",
    highlights: [
      "주식 자동매매 프로젝트 진입점",
      "Python 기반 운영 스크립트 레포",
      "분석, 주문, 알림 흐름의 문서화 대상",
      "원본 GitHub 이슈와 저장소 연결"
    ],
    stack: ["Python", "Stock", "Automation", "Trading"],
    sourceRepo: "jhny-kor/AutoStockTrading",
    repoUrl: "https://github.com/jhny-kor/AutoStockTrading",
    referenceUrl: "https://github.com/jhny-kor/AutoStockTrading",
    pagePath: "./auto-stock-trading/",
    supportUrl: "https://github.com/jhny-kor/AutoStockTrading/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "remote-control",
    name: "RemoteControl",
    mark: "RC",
    status: "참조",
    statusTone: "reference",
    type: "macOS Automation",
    category: "automation",
    summary: "Codex와 로컬 macOS 프로젝트를 원격으로 관리하는 Python/Telegram 기반 매니저입니다.",
    description: "RemoteControl은 Codex 작업, 로컬 프로젝트, Telegram 명령을 연결하는 원격 제어 매니저입니다. 대표 페이지에서는 운영 대상과 자동화 링크를 명확히 분리합니다.",
    highlights: [
      "Codex 및 로컬 macOS 프로젝트 원격 관리",
      "Telegram bot 기반 제어 흐름",
      "Python 자동화 스크립트 중심",
      "remote-control, macos, automation 토픽"
    ],
    stack: ["Python", "Telegram", "macOS", "Codex"],
    sourceRepo: "jhny-kor/RemoteControl",
    repoUrl: "https://github.com/jhny-kor/RemoteControl",
    referenceUrl: "https://github.com/jhny-kor/RemoteControl",
    pagePath: "./remote-control/",
    supportUrl: "https://github.com/jhny-kor/RemoteControl/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "sec-chk",
    name: "sec-chk",
    mark: "SC",
    status: "참조",
    statusTone: "reference",
    type: "Security Tool",
    category: "app",
    summary: "보안 점검과 스캐닝 도구를 다루는 Swift 기반 프로젝트입니다.",
    description: "sec-chk는 security scanner와 security tools 토픽을 가진 보안 점검 프로젝트입니다. 대표 페이지에서는 저장소, 목적, 지원 경로를 간결하게 제공합니다.",
    highlights: [
      "Security Check 프로젝트",
      "Swift 기반 보안 도구 표면",
      "security-scanner, security-tools 토픽",
      "이슈 기반 개선 요청 연결"
    ],
    stack: ["Swift", "Security", "Scanner", "Tooling"],
    sourceRepo: "jhny-kor/sec-chk",
    repoUrl: "https://github.com/jhny-kor/sec-chk",
    referenceUrl: "https://github.com/jhny-kor/sec-chk",
    pagePath: "./sec-chk/",
    supportUrl: "https://github.com/jhny-kor/sec-chk/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "fashion-trend",
    name: "fashion-trend",
    mark: "FT",
    status: "참조",
    statusTone: "reference",
    type: "Report Site",
    category: "site",
    summary: "KREAM 크롤링으로 실시간 패션 트렌드를 수집하고 다크 매거진 스타일 HTML 리포트를 생성합니다.",
    description: "fashion-trend는 패션 트렌드 데이터를 수집하고 HTML 리포트로 전환하는 자동화 프로젝트입니다. 대표 페이지에서는 리포트 성격과 원본 레포를 명확히 보여줍니다.",
    highlights: [
      "KREAM 기반 실시간 패션 트렌드 수집",
      "다크 매거진 스타일 HTML 리포트 생성",
      "Claude Code 스킬로 활용 가능한 구조",
      "콘텐츠 리포트 자동화 프로젝트"
    ],
    stack: ["Crawler", "HTML Report", "Fashion", "Automation"],
    sourceRepo: "jhny-kor/fashion-trend",
    repoUrl: "https://github.com/jhny-kor/fashion-trend",
    referenceUrl: "https://github.com/jhny-kor/fashion-trend",
    pagePath: "./fashion-trend/",
    supportUrl: "https://github.com/jhny-kor/fashion-trend/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "ai-news",
    name: "AI-News",
    mark: "AI",
    status: "참조",
    statusTone: "reference",
    type: "Pages",
    category: "site",
    summary: "AI 관련 페이지와 뉴스성 콘텐츠를 정리하기 위한 Pages 프로젝트입니다.",
    description: "AI-News는 공개 레포 설명 기준으로 AI pages를 제공하는 프로젝트입니다. gomgom-dev 대표 사이트에서는 향후 뉴스, 리포트, 정리 페이지의 진입점으로 둡니다.",
    highlights: [
      "AI 관련 Pages 프로젝트",
      "뉴스와 리포트형 콘텐츠 확장 대상",
      "정적 사이트로 배포하기 쉬운 구조",
      "대표 허브에서 Sites 그룹으로 분류"
    ],
    stack: ["AI", "Pages", "Content", "Static Site"],
    sourceRepo: "jhny-kor/AI-News",
    repoUrl: "https://github.com/jhny-kor/AI-News",
    referenceUrl: "https://github.com/jhny-kor/AI-News",
    pagePath: "./ai-news/",
    supportUrl: "https://github.com/jhny-kor/AI-News/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "porta-pages",
    name: "porta-pages",
    mark: "PP",
    status: "참조",
    statusTone: "reference",
    type: "Support Pages",
    category: "site",
    summary: "porta App Store listing을 위한 지원 및 개인정보 페이지 모음입니다.",
    description: "porta-pages는 앱스토어 제출에 필요한 support, privacy 문서를 제공하는 HTML 기반 레포입니다. 대표 페이지에서는 정책성 문서 프로젝트로 분리합니다.",
    highlights: [
      "App Store listing 지원 페이지",
      "Privacy 문서와 지원 채널 관리",
      "HTML 기반 정적 페이지",
      "앱 제출용 문서 레포"
    ],
    stack: ["HTML", "Support", "Privacy", "App Store"],
    sourceRepo: "jhny-kor/porta-pages",
    repoUrl: "https://github.com/jhny-kor/porta-pages",
    referenceUrl: "https://github.com/jhny-kor/porta-pages",
    pagePath: "./porta-pages/",
    supportUrl: "https://github.com/jhny-kor/porta-pages/issues",
    policyUrl: "./privacy-policy/"
  },
  {
    slug: "claw-code",
    name: "claw-code",
    mark: "CC",
    status: "참조",
    statusTone: "reference",
    type: "Developer Tool",
    category: "app",
    summary: "Claude Code 아카이브를 넘어 실제 개발 작업을 수행하는 도구 실험 레포입니다.",
    description: "claw-code는 jhny-kor 공개 레포 중 개발 도구 성격이 강한 프로젝트입니다. 대표 페이지에서는 원본 레포와 현재 설명을 보존하고 별도 프로젝트 폴더로 분리합니다.",
    highlights: [
      "Developer tooling 실험 프로젝트",
      "Rust rewrite 언급이 있는 공개 레포",
      "도구형 프로젝트로 Apps 그룹에 포함",
      "원본 설명과 레포 링크 보존"
    ],
    stack: ["Developer Tool", "Rust", "CLI", "Experiment"],
    sourceRepo: "jhny-kor/claw-code",
    repoUrl: "https://github.com/jhny-kor/claw-code",
    referenceUrl: "https://github.com/jhny-kor/claw-code",
    pagePath: "./claw-code/",
    supportUrl: "https://github.com/jhny-kor/claw-code/issues",
    policyUrl: "./privacy-policy/"
  }
];
